image: python:3.10.0
options:
  docker: true
  size: 2x

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:1.4.0
            variables:
            SONAR_TOKEN: ${SONAR_TOKEN}
        services:
          - docker

    - step: &check-quality-gate-sonarcloud
        name: Check the Quality Gate on SonarCloud
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
        services:
          - docker
  services:
    docker:
      memory: 4096

pipelines: # More info here: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
  branches:
    master:
      - step: *build-test-sonarcloud
        services:
          - docker
      - step: *check-quality-gate-sonarcloud
        services:
          - docker

    develop:
      - step: *build-test-sonarcloud
        services:
          - docker
      - step: *check-quality-gate-sonarcloud
        services:
          - docker
  pull-requests:
    "**":
      - step: *build-test-sonarcloud
        services:
          - docker
      - step: *check-quality-gate-sonarcloud
        services:
          - docker
